import { BaseResource } from '../../shared/infrastructure/base-response';

/**
 * Resource representation of an authenticated user session.
 *
 * @remarks
 * This resource belongs to the infrastructure layer and represents the session
 * built after a successful sign-in. The token is a mock value generated by the
 * frontend because there is no authentication backend yet.
 *
 * @example
 * ```typescript
 * const resource: SignInResource = {
 *   id: 1,
 *   name: 'BevTrace Admin',
 *   email: 'bevtrace@admin.com',
 *   roles: ['ROLE_ADMIN'],
 *   token: 'bW9jay10b2tlbg=='
 * };
 * ```
 */
export interface SignInResource extends BaseResource {
  /**
   * The unique numeric identifier of the authenticated user.
   */
  id: number;

  /**
   * The full name of the authenticated user.
   */
  name: string;

  /**
   * The e-mail address of the authenticated user.
   */
  email: string;

  /**
   * Authorization roles assigned to the authenticated user.
   */
  roles: string[];

  /**
   * Mock access token attached to outgoing requests.
   */
  token: string;
}
